version: "3.9"

services:
  web-app:
    image: "flask-prueba:latest"
    ports:
      - "5050:5000"
  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
      # Mount this code into /code
      - ./code:/code
      # Mount the docker socke
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_HOOKS_DIR=/code/hooks
      - WEBHOOK_BRANCH_LIST=master
    expose:
      - 8000